name: pyptv
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - cython
  - fonttools
  - imagecodecs
  - libffi
  - libzlib
  - numpy
  - openssl
  - pillow
  - pip
  - pygments
  - pyparsing
  - python
  - pyyaml
  - scikit-image
  - setuptools
  - six
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - swig
  - pyqt
  - traits
  - traitsui
  - tqdm
  - pip:
    - --index-url https://pypi.fury.io/pyptv --extra-index-url https://pypi.org/simple
    - git+https://github.com/enthought/enable
    - chaco
    - optv
    - git+https://github.com/alexlib/pyptv