name: pyptv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - numpy
    - --index-url https://pypi.fury.io/pyptv --extra-index-url https://pypi.org/simple
    - git+https://github.com/alexlib/pyptv